name = "mbgifts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"            # 這是程式裡使用的變數名稱
database_name = "mbg-db"  # 你在 Cloudflare D1 建的資料庫名稱
database_id = "9166a7b1-f4ad-4120-8b82-14302e725d67"
