name = "mbgifts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"            # 這是程式裡使用的變數名稱
database_name = "mbg-db"  # 你在 Cloudflare D1 建的資料庫名稱
database_id = "9e4094af-2915-4bba-bb33-63efaadec8bc"

# 綁定 R2
[[r2_buckets]]
binding = "R2"                 # 程式內使用的變數名
bucket_name = "gift-images"
